/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package linguistic;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author user
 */
public class TagInfoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form WordInfoJFrame
     */
    public TagInfoJFrame() {
        initComponents();
        tagInfoTextArea.setText("Number	Tag	Description\n");
        tagInfoTextArea.append("1.	CC	Coordinating conjunction\n" +
                            "2.	CD	Cardinal number\n" +
                            "3.	DT	Determiner\n" +
                            "4.	EX	Existential there\n" +
                            "5.	FW	Foreign word\n" +
                            "6.	IN	Preposition or subordinating conjunction\n" +
                            "7.	JJ	Adjective\n" +
                            "8.	JJR	Adjective, comparative\n" +
                            "9.	JJS	Adjective, superlative\n" +
                            "10.	LS	List item marker\n" +
                            "11.	MD	Modal\n" +
                            "12.	NN	Noun, singular or mass\n" +
                            "13.	NNS	Noun, plural\n" +
                            "14.	NNP	Proper noun, singular\n" +
                            "15.	NNPS	Proper noun, plural\n" +
                            "16.	PDT	Predeterminer\n" +
                            "17.	POS	Possessive ending\n" +
                            "18.	PRP	Personal pronoun\n" +
                            "19.	PRP$	Possessive pronoun\n" +
                            "20.	RB	Adverb\n" +
                            "21.	RBR	Adverb, comparative\n" +
                            "22.	RBS	Adverb, superlative\n" +
                            "23.	RP	Particle\n" +
                            "24.	SYM	Symbol\n" +
                            "25.	TO	to\n" +
                            "26.	UH	Interjection\n" +
                            "27.	VB	Verb, base form\n" +
                            "28.	VBD	Verb, past tense\n" +
                            "29.	VBG	Verb, gerund or present participle\n" +
                            "30.	VBN	Verb, past participle\n" +
                            "31.	VBP	Verb, non-3rd person singular present\n" +
                            "32.	VBZ	Verb, 3rd person singular present\n" +
                            "33.	WDT	Wh-determiner\n" +
                            "34.	WP	Wh-pronoun\n" +
                            "35.	WP$	Possessive wh-pronoun\n" +
                            "36.	WRB	Wh-adverb");
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                setVisible(false);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tagInfoTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tag information");

        closeButton.setText("OK");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        tagInfoTextArea.setColumns(20);
        tagInfoTextArea.setRows(5);
        tagInfoTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tagInfoTextArea.setEnabled(false);
        jScrollPane1.setViewportView(tagInfoTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tagInfoTextArea;
    // End of variables declaration//GEN-END:variables
}
